export const DBErrors = {
    INVALID_NUMBER_ROWS: 'INVALID_NUMBER_ROWS',
    INVALID_NUMBER_COLUMNS: 'INVALID_NUMBER_COLUMNS',
    INVALID_FIELD_VARIANCE: 'INVALID_FIELD_VARIANCE',
    NO_ITEM_TABLE: 'NO_ITEM_TABLE',
    NO_ITEM_ROWS: 'NO_ITEM_ROWS',
}
